apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: cluster-api
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec: {}
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
  relatedObjects:
  - group: config.openshift.io
    name: cluster-api
    resource: clusteroperators
  - group: ""
    name: openshift-cluster-api
    resource: namespaces
  - group: ""
    name: cluster-capi-operator
    namespace: openshift-cluster-api
    resource: serviceaccounts
  - group: ""
    name: cluster-capi-operator-images
    namespace: openshift-cluster-api
    resource: configmaps
  - group: "apps"
    name: cluster-capi-operator
    namespace: openshift-cluster-api
    resource: deployments
