apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-capi-operator-images
  namespace: openshift-cluster-api
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
data:
  images.json: >
    {
      "cluster-capi-operator": "quay.io/openshift/origin-cluster-capi-operator",
      "cluster-api:operator": "quay.io/asalkeld/cluster-api-operator-amd64:dev",
      "bootstrap-kubeadm:manager": "k8s.gcr.io/cluster-api/kubeadm-bootstrap-controller:v0.4.3",
      "controlplane-kubeadm:manager": "k8s.gcr.io/cluster-api/kubeadm-control-plane-controller:v0.4.3",
      "core-cluster-api:manager": "k8s.gcr.io/cluster-api/cluster-api-controller:v0.4.3",
      "infrastructure-aws:manager": "k8s.gcr.io/cluster-api-aws/cluster-api-aws-controller:v0.7.0",
      "infrastructure-azure:manager": "us.gcr.io/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller:v0.5.2",
      "infrastructure-metal3:ip-address-manager": "quay.io/metal3-io/ip-address-manager:v0.1.0",
      "infrastructure-metal3:manager": "quay.io/metal3-io/cluster-api-provider-metal3:v0.5.0",
      "kube-rbac-proxy": "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0"
    }
